raw_data_dir: '/home/dle/dat/learn/spark/movie_lens_project/data/raw/ml-1m'
extract_data_dir: '/home/dle/dat/learn/spark/movie_lens_project/data/extracted'
transform_data_dir: '/home/dle/dat/learn/spark/movie_lens_project/data/transformed'
